### ISSUE TITLE
An issue regarding errors when running code

### ISSUE THREAD

**Issue by hengheng1266** [Ratun11/P_MetaSGD#3]
Has anyone reported the following error while running "multi_task_fed. py"?

  File "E:\P_MetaSGD-main\multi_task_fed.py", line 150, in <module>
    server_fedAvg(global_model, client_models)
  File "E:\P_MetaSGD-main\multi_task_fed.py", line 115, in server_fedAvg
    weights_sum[i] += client_weights[i] * calculate_weight_for_client(accuracy, i)
  File "E:\P_MetaSGD-main\multi_task_fed.py", line 102, in calculate_weight_for_client
    weight = accuracy[i]
TypeError: 'float' object is not subscriptable

**Comment by hengheng1266** [comment]
A similar issue occurred while running “Differential_privacy_fed.py”

2024-03-22 15:50:21.846061: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 983040000 exceeds 10% of free system memory.
Traceback (most recent call last):
  File "E:\P_MetaSGD-main\Differential_privacy_fed.py", line 63, in <module>
    server_fedAvg(global_model, client_models)
  File "E:\P_MetaSGD-main\Differential_privacy_fed.py", line 34, in server_fedAvg
    weights_sum[i] += client_weights[i]*(accuracy[i]*1.85)
TypeError: 'float' object is not subscriptable
